version: "2"

linters:
  default: none

  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - durationcheck
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gomoddirectives
    - govet
    - ineffassign
    - misspell
    - mnd
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
    - wastedassign
    - whitespace
  settings:
    revive:
      # see: https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md
      rules:
        - name: context-as-argument
          arguments:
            - allowTypesBefore: '*testing.T,*testing.B,*testing.F'
#        - name: context-keys-type
        - name: duplicated-imports
        - name: early-return
        - name: error-naming
        - name: errorf
        - name: package-comments
          disabled: true
        - name: time-equal
        - name: unnecessary-stmt
        - name: use-any
        - name: useless-break
        - name: var-declaration
        - name: var-naming
        - name: waitgroup-by-value
    gomoddirectives:
      replace-local: true
      replace-allow-list:
        - addcn
        - tw8591
      toolchain-forbidden: true
      go-version-pattern: '^1\.24\.0$'
    nolintlint:
      require-specific: true

formatters:
  enable:
    - gofumpt
    - goimports