package slices

import (
	"math/rand/v2"
	"slices"

	"github.com/go-fries/fries/constraints/v3"
)

// Map returns a new slice containing the results of applying fn to each item in s.
//
//	Map([]int{1, 2, 3}, func(i int) int { return i * 2 }) // []int{2, 4, 6}
//	Map([]string{"a", "b", "c"}, func(s string) string { return s + "!" }) // []string{"a!", "b!", "c!"}
func Map[S ~[]E, E, R any](s S, fn func(E) R) []R {
	result := make([]R, 0, len(s))
	for _, item := range s {
		result = append(result, fn(item))
	}
	return result
}

// MapN returns a new slice containing the results of applying fn to each item in s.
// The current index is passed to fn as the second argument.
//
//	Map([]int{1, 2, 3}, func(i, _ int) int { return i * 2 }) // []int{2, 4, 6}
//	Map([]string{"a", "b", "c"}, func(s string, _ int) string { return s + "!" }) // []string{"a!", "b!", "c!"}
func MapN[S ~[]E, E, R any](s S, fn func(E, int) R) []R {
	result := make([]R, 0, len(s))
	for i, item := range s {
		result = append(result, fn(item, i))
	}
	return result
}

// FlatMap returns a new slice containing the concatenated results of applying
// fn to each item in s.
//
//	FlatMap([]int{1, 2}, func(i int) []int { return []int{i, i * 10} }) // []int{1, 10, 2, 20}
func FlatMap[S ~[]E, E, R any](s S, fn func(E) []R) []R {
	result := make([]R, 0, len(s))
	for _, item := range s {
		result = append(result, fn(item)...)
	}
	return result
}

// KeyMap returns a new map containing keys and values generated by applying fn
// to each item in s.
//
//	KeyMap([]int{1, 2, 3}, func(i, _ int) (int, int) { return i, i * 2 }) // map[int]int{1: 2, 2: 4, 3: 6}
//	KeyMap([]string{"a", "b", "c"}, func(s string, _ int) (string, string) {
//		return s, s + "!"
//	}) // map[string]string{"a": "a!", "b": "b!", "c": "c!"}
func KeyMap[S ~[]E, E, R any, K comparable](s S, fn func(E, int) (K, R)) map[K]R {
	result := make(map[K]R)
	for i, item := range s {
		key, value := fn(item, i)
		result[key] = value
	}
	return result
}

// Each calls fn for each item in s.
//
//	Each([]int{1, 2, 3}, func(i int) { fmt.Println(i) }) // 1\n2\n3
func Each[S ~[]E, E any](s S, fn func(E)) {
	for _, item := range s {
		fn(item)
	}
}

// EachN calls fn for each item in s.
// The current index is passed to fn as the second argument.
//
//	EachN([]int{1, 2, 3}, func(i int, _ int) { fmt.Println(i) }) // 1\n2\n3
func EachN[S ~[]E, E any](s S, fn func(E, int)) {
	for i, item := range s {
		fn(item, i)
	}
}

// Prepend returns s with items added to the beginning.
//
//	Prepend([]int{1, 2, 3}, 4, 5) // []int{4, 5, 1, 2, 3}
func Prepend[S ~[]E, E any](s S, items ...E) S {
	return append(items, s...)
}

// Append returns s with items added to the end.
//
//	Append([]int{1, 2, 3}, 4, 5) // []int{1, 2, 3, 4, 5}
func Append[S ~[]E, E any](s S, items ...E) S {
	return append(s, items...)
}

// Filter returns a new slice containing the items in s that satisfy fn.
//
//	Filter([]int{1, 2, 3}, func(i int) bool { return i > 1 }) // []int{2, 3}
//	Filter([]string{"a", "b", "c"}, func(s string) bool { return s != "b" }) // []string{"a", "c"}
func Filter[S ~[]E, E any](s S, fn func(E) bool) S {
	var result S
	for _, item := range s {
		if fn(item) {
			result = append(result, item)
		}
	}
	return result
}

// FilterN returns a new slice containing the items in s that satisfy fn.
// The current index is passed to fn as the second argument.
//
//	FilterN([]int{1, 2, 3}, func(i int, _ int) bool { return i > 1 }) // []int{2, 3}
//	FilterN([]string{"a", "b", "c"}, func(s string, _ int) bool { return s != "b" }) // []string{"a", "c"}
func FilterN[S ~[]E, E any](s S, fn func(E, int) bool) S {
	var result S
	for i, item := range s {
		if fn(item, i) {
			result = append(result, item)
		}
	}
	return result
}

// Any reports whether any item in s satisfies fn.
//
//	Any([]int{1, 2, 3}, func(i int) bool { return i > 2 }) // true
func Any[S ~[]E, E any](s S, fn func(E) bool) bool {
	return slices.ContainsFunc(s, fn)
}

// Every reports whether every item in s satisfies fn.
//
// Every returns true for an empty slice.
//
//	Every([]int{1, 2, 3}, func(i int) bool { return i > 0 }) // true
func Every[S ~[]E, E any](s S, fn func(E) bool) bool {
	for _, item := range s {
		if !fn(item) {
			return false
		}
	}
	return true
}

// Reduce applies fn against an accumulator and each item in s to reduce it to a
// single value.
//
//	Reduce([]int{1, 2, 3}, func(acc, i int) int { return acc + i }, 0) // 6
//	Reduce([]string{"a", "b", "c"}, func(acc, s string) string { return acc + s }, "") // "abc"
//	Reduce([]int{1, 2, 3}, func(acc, i int) int { return acc + i }, 5) // 11
func Reduce[S ~[]E, E, R any](s S, fn func(R, E) R, defaults ...R) R {
	var result R
	if len(defaults) > 0 {
		result = defaults[0]
	}
	for _, item := range s {
		result = fn(result, item)
	}
	return result
}

// ReduceN applies fn against an accumulator and each item in s to reduce it to a
// single value. The current index is passed to fn as the third argument.
//
//	ReduceN([]int{1, 2, 3}, func(acc, i, _ int) int { return acc + i }, 0) // 6
//	ReduceN([]string{"a", "b", "c"}, func(acc, s string, _ int) string { return acc + s }, "") // "abc"
//	ReduceN([]int{1, 2, 3}, func(acc, i, _ int) int { return acc + i }, 5) // 11
func ReduceN[S ~[]E, E, R any](s S, fn func(R, E, int) R, defaults ...R) R {
	var result R
	if len(defaults) > 0 {
		result = defaults[0]
	}
	for i, item := range s {
		result = fn(result, item, i)
	}
	return result
}

// Reverse returns a new slice containing the items in s in reverse order.
//
//	Reverse([]int{1, 2, 3}) // []int{3, 2, 1}
func Reverse[S ~[]E, E any](s S) S {
	result := make(S, len(s))
	for i := 0; i < len(s); i++ {
		result[i] = s[len(s)-1-i]
	}
	return result
}

// Concat returns a new slice containing the items of all given slices.
//
//	Concat([]int{1, 2}, []int{3, 4}, []int{5, 6}) // []int{1, 2, 3, 4, 5, 6}
func Concat[S ~[]E, E any](slices ...S) S {
	var totalLen int
	for _, slice := range slices {
		totalLen += len(slice)
	}

	result := make(S, 0, totalLen)
	for _, slice := range slices {
		result = append(result, slice...)
	}
	return result
}

// IsEmpty reports whether s is empty.
//
//	IsEmpty([]int{}) // true
//	IsEmpty([]int{1, 2, 3}) // false
func IsEmpty[S ~[]E, E any](s S) bool {
	return len(s) == 0
}

// IsNotEmpty reports whether s is not empty.
//
//	IsNotEmpty([]int{}) // false
//	IsNotEmpty([]int{1, 2, 3}) // true
func IsNotEmpty[S ~[]E, E any](s S) bool {
	return len(s) > 0
}

// IndexOf returns the index of the first occurrence of e in s, or -1 if e is
// not present.
//
//	IndexOf([]int{1, 2, 3}, 2) // 1
//	IndexOf([]string{"a", "b", "c"}, "d") // -1
func IndexOf[S ~[]E, E comparable](s S, e E) int {
	for i, item := range s {
		if item == e {
			return i
		}
	}
	return -1
}

// LastIndexOf returns the index of the last occurrence of e in s, or -1 if e is
// not present.
//
//	LastIndexOf([]int{1, 2, 3, 2}, 2) // 3
//	LastIndexOf([]string{"a", "b", "c"}, "d") // -1
func LastIndexOf[S ~[]E, E comparable](s S, e E) int {
	for i := len(s) - 1; i >= 0; i-- {
		if s[i] == e {
			return i
		}
	}
	return -1
}

// Unique returns a new slice containing the unique items in s.
//
//	Unique([]int{1, 2, 2, 3, 3, 3}) // []int{1, 2, 3}
//	Unique([]string{"a", "b", "b", "c", "c", "c"}) // []string{"a", "b", "c"}
func Unique[S ~[]E, E comparable](s S) S {
	var result S
	seeds := make(map[E]struct{})
	for _, item := range s {
		if _, ok := seeds[item]; !ok {
			seeds[item] = struct{}{}
			result = append(result, item)
		}
	}
	return result
}

// UniqueBy returns a new slice containing the unique items in s based on the
// key returned by fn.
//
//	UniqueBy([]string{"apple", "apple2", "cherry"}, func(s string) string {
//		return s[:1]
//	}) // []string{"apple", "cherry"}
func UniqueBy[S ~[]E, E any, K comparable](s S, fn func(E) K) S {
	var result S
	seeds := make(map[K]struct{})
	for _, item := range s {
		key := fn(item)
		if _, ok := seeds[key]; !ok {
			seeds[key] = struct{}{}
			result = append(result, item)
		}
	}
	return result
}

// UniqueByN returns a new slice containing the unique items in s based on the
// key returned by fn. The current index is passed to fn as the second argument.
//
//	UniqueByN([]string{"apple", "apple2", "cherry"}, func(s string, _ int) string {
//		return s[:1]
//	}) // []string{"apple", "cherry"}
func UniqueByN[S ~[]E, E any, K comparable](s S, fn func(E, int) K) S {
	var result S
	seeds := make(map[K]struct{})
	for i, item := range s {
		key := fn(item, i)
		if _, ok := seeds[key]; !ok {
			seeds[key] = struct{}{}
			result = append(result, item)
		}
	}
	return result
}

// Difference returns a new slice containing items in s1 that are not present in
// s2.
//
//	Difference([]int{1, 2, 3}, []int{2, 3, 4}) // []int{1}
//	Difference([]string{"a", "b", "c"}, []string{"b", "c", "d"}) // []string{"a"}
func Difference[S ~[]E, E comparable](s1, s2 S) S {
	var result S
	for _, item := range s1 {
		if !slices.Contains(s2, item) {
			result = append(result, item)
		}
	}
	return result
}

// Intersect returns a new slice containing items in s1 that are also present in
// s2.
//
//	Intersect([]int{1, 2, 3}, []int{2, 3, 4}) // []int{2, 3}
//	Intersect([]string{"a", "b", "c"}, []string{"b", "c", "d"}) // []string{"b", "c"}
func Intersect[S ~[]E, E comparable](s1, s2 S) S {
	var result S
	for _, item := range s1 {
		if slices.Contains(s2, item) {
			result = append(result, item)
		}
	}
	return result
}

// Only returns a new slice containing only the selected items from s.
//
//	Only([]int{1, 2, 3}, 2, 3) // []int{2, 3}
//	Only([]string{"a", "b", "c"}, "b", "c") // []string{"b", "c"}
func Only[S ~[]E, E comparable](s S, items ...E) S {
	var result S
	for _, item := range s {
		if slices.Contains(items, item) {
			result = append(result, item)
		}
	}
	return result
}

// Without returns a new slice without the selected items from s.
//
//	Without([]int{1, 2, 3}, 2, 3) // []int{1}
//	Without([]string{"a", "b", "c"}, "b", "c") // []string{"a"}
func Without[S ~[]E, E comparable](s S, items ...E) S {
	var result S
	for _, item := range s {
		if !slices.Contains(items, item) {
			result = append(result, item)
		}
	}
	return result
}

// Remove returns a new slice without the selected items from s.
// Remove is an alias for [Without].
//
//	Remove([]int{1, 2, 3}, 2, 3) // []int{1}
//	Remove([]string{"a", "b", "c"}, "b", "c") // []string{"a"}
func Remove[S ~[]E, E comparable](s S, items ...E) S {
	return Without(s, items...)
}

// Partition returns two new slices. The first contains items in s that satisfy
// fn, and the second contains items that do not satisfy fn.
//
//	Partition([]int{1, 2, 3}, func(i int) bool { return i > 1 }) // ([]int{2, 3}, []int{1})
func Partition[S ~[]E, E any](s S, fn func(E) bool) (yes, no S) {
	for _, item := range s {
		if fn(item) {
			yes = append(yes, item)
		} else {
			no = append(no, item)
		}
	}
	return yes, no
}

// PartitionN returns two new slices. The first contains items in s that satisfy
// fn, and the second contains items that do not satisfy fn. The current index is
// passed to fn as the second argument.
//
//	PartitionN([]int{1, 2, 3}, func(i, idx int) bool { return i > 1 }) // ([]int{2, 3}, []int{1})
func PartitionN[S ~[]E, E any](s S, fn func(E, int) bool) (yes, no S) {
	for i, item := range s {
		if fn(item, i) {
			yes = append(yes, item)
		} else {
			no = append(no, item)
		}
	}
	return yes, no
}

// Chunk returns a new slice containing the items in s chunked into smaller
// slices of size.
//
// If size is less than or equal to zero, Chunk returns nil.
//
//	Chunk([]int{1, 2, 3, 4, 5}, 2) // [][]int{{1, 2}, {3, 4}, {5}}
//	Chunk([]string{"a", "b", "c", "d", "e"}, 2) // [][]string{{"a", "b"}, {"c", "d"}, {"e"}}
func Chunk[S ~[]E, E any](s S, size int) (result []S) {
	if size <= 0 {
		return nil
	}

	length := len(s)
	for i := 0; i < length; i += size {
		end := min(i+size, length)
		result = append(result, s[i:end])
	}
	return result
}

// GroupBy returns a new map containing the items in s grouped by the key
// returned by fn.
//
//	GroupBy([]int{1, 2, 3, 4, 5}, func(i int) int { return i % 2 }) // map[int][]int{0: {2, 4}, 1: {1, 3, 5}}
func GroupBy[S ~[]E, E any, K comparable](s S, fn func(E) K) map[K]S {
	result := make(map[K]S)
	for _, item := range s {
		key := fn(item)
		result[key] = append(result[key], item)
	}
	return result
}

// GroupByN returns a new map containing the items in s grouped by the key
// returned by fn. The current index is passed to fn as the second argument.
//
//	GroupByN([]int{1, 2, 3, 4, 5}, func(i, idx int) int { return i % 2 }) // map[int][]int{0: {2, 4}, 1: {1, 3, 5}}
func GroupByN[S ~[]E, E any, K comparable](s S, fn func(E, int) K) map[K]S {
	result := make(map[K]S)
	for i, item := range s {
		key := fn(item, i)
		result[key] = append(result[key], item)
	}
	return result
}

// CountBy returns a new map containing item counts grouped by the key returned
// by fn.
//
//	CountBy([]int{1, 2, 3, 4}, func(i int) string {
//		if i%2 == 0 {
//			return "even"
//		}
//		return "odd"
//	}) // map[string]int{"even": 2, "odd": 2}
func CountBy[S ~[]E, E any, K comparable](s S, fn func(E) K) map[K]int {
	result := make(map[K]int)
	for _, item := range s {
		key := fn(item)
		result[key]++
	}
	return result
}

// First returns the first item in s, or a zero value and false if s is empty.
//
//	First([]int{1, 2, 3}) // 1, true
//	First([]int{}) // 0, false
func First[S ~[]E, E any](s S) (E, bool) {
	if len(s) == 0 {
		var zero E
		return zero, false
	}
	return s[0], true
}

// Last returns the last item in s, or a zero value and false if s is empty.
//
//	Last([]int{1, 2, 3}) // 3, true
//	Last([]int{}) // 0, false
func Last[S ~[]E, E any](s S) (E, bool) {
	if len(s) == 0 {
		var zero E
		return zero, false
	}
	return s[len(s)-1], true
}

// Find returns the first item in s that satisfies fn, or a zero value and false
// if no item satisfies fn.
//
//	Find([]int{1, 2, 3}, func(i int) bool { return i > 1 }) // 2, true
//	Find([]int{1, 2, 3}, func(i int) bool { return i > 3 }) // 0, false
func Find[S ~[]E, E any](s S, fn func(E) bool) (E, bool) {
	for _, item := range s {
		if fn(item) {
			return item, true
		}
	}
	var zero E
	return zero, false
}

// FindN returns the first item in s that satisfies fn, or a zero value and false
// if no item satisfies fn. The current index is passed to fn as the second
// argument.
//
//	FindN([]int{1, 2, 3}, func(i, idx int) bool { return i > 1 }) // 2, true
//	FindN([]int{1, 2, 3}, func(i, idx int) bool { return i > 3 }) // 0, false
func FindN[S ~[]E, E any](s S, fn func(E, int) bool) (E, bool) {
	for i, item := range s {
		if fn(item, i) {
			return item, true
		}
	}
	var zero E
	return zero, false
}

// FindLast returns the last item in s that satisfies fn, or a zero value and
// false if no item satisfies fn.
//
//	FindLast([]int{1, 2, 3}, func(i int) bool { return i > 1 }) // 3, true
//	FindLast([]int{1, 2, 3}, func(i int) bool { return i > 3 }) // 0, false
func FindLast[S ~[]E, E any](s S, fn func(E) bool) (E, bool) {
	for i := len(s) - 1; i >= 0; i-- {
		item := s[i]
		if fn(item) {
			return item, true
		}
	}
	var zero E
	return zero, false
}

// FindLastN returns the last item in s that satisfies fn, or a zero value and
// false if no item satisfies fn. The current index is passed to fn as the second
// argument.
//
//	FindLastN([]int{1, 2, 3}, func(i, idx int) bool { return i > 1 }) // 3, true
//	FindLastN([]int{1, 2, 3}, func(i, idx int) bool { return i > 3 }) // 0, false
func FindLastN[S ~[]E, E any](s S, fn func(E, int) bool) (E, bool) {
	for i := len(s) - 1; i >= 0; i-- {
		item := s[i]
		if fn(item, i) {
			return item, true
		}
	}
	var zero E
	return zero, false
}

// Index returns the index of the first item in s that satisfies fn, or -1 and
// false if no item satisfies fn.
//
//	Index([]int{1, 2, 3}, func(i int) bool { return i > 1 }) // 1, true
//	Index([]int{1, 2, 3}, func(i int) bool { return i > 3 }) // -1, false
func Index[S ~[]E, E any](s S, fn func(E) bool) (int, bool) {
	for i, item := range s {
		if fn(item) {
			return i, true
		}
	}
	return -1, false
}

// IndexN returns the index of the first item in s that satisfies fn, or -1 and
// false if no item satisfies fn. The current index is passed to fn as the second
// argument.
//
//	IndexN([]int{1, 2, 3}, func(i, idx int) bool { return i > 1 }) // 1, true
//	IndexN([]int{1, 2, 3}, func(i, idx int) bool { return i > 3 }) // -1, false
func IndexN[S ~[]E, E any](s S, fn func(E, int) bool) (int, bool) {
	for i, item := range s {
		if fn(item, i) {
			return i, true
		}
	}
	return -1, false
}

// LastIndex returns the index of the last item in s that satisfies fn, or -1
// and false if no item satisfies fn.
//
//	LastIndex([]int{1, 2, 3}, func(i int) bool { return i > 1 }) // 2, true
//	LastIndex([]int{1, 2, 3}, func(i int) bool { return i > 3 }) // -1, false
func LastIndex[S ~[]E, E any](s S, fn func(E) bool) (int, bool) {
	for i := len(s) - 1; i >= 0; i-- {
		if fn(s[i]) {
			return i, true
		}
	}
	return -1, false
}

// LastIndexN returns the index of the last item in s that satisfies fn, or -1
// and false if no item satisfies fn. The current index is passed to fn as the
// second argument.
//
//	LastIndexN([]int{1, 2, 3}, func(i, idx int) bool { return i > 1 }) // 2, true
//	LastIndexN([]int{1, 2, 3}, func(i, idx int) bool { return i > 3 }) // -1, false
func LastIndexN[S ~[]E, E any](s S, fn func(E, int) bool) (int, bool) {
	for i := len(s) - 1; i >= 0; i-- {
		if fn(s[i], i) {
			return i, true
		}
	}
	return -1, false
}

// Fill sets every item in s to value and returns s.
//
//	Fill([]int{1, 2, 3}, 0) // []int{0, 0, 0}
//	Fill(make([]int, 3), 1) // []int{1, 1, 1}
func Fill[S ~[]E, E any](s S, value E) S {
	for i := range s {
		s[i] = value
	}
	return s
}

// Random returns a random item from s.
//
// Random uses math/rand/v2 and returns the zero value if s is empty.
//
//	Random([]int{1, 2, 3}) // 2
//	Random([]string{"a", "b", "c"}) // "b"
func Random[S ~[]E, E any](s S) E {
	if len(s) == 0 {
		var zero E
		return zero
	}
	return s[rand.IntN(len(s))]
}

// Shuffle returns a new slice containing the items in s shuffled.
//
//	Shuffle([]int{1, 2, 3}) // []int{3, 1, 2}
func Shuffle[S ~[]E, E any](s S) S {
	result := make(S, len(s))
	copy(result, s)
	rand.Shuffle(len(result), func(i, j int) {
		result[i], result[j] = result[j], result[i]
	})
	return result
}

// Min returns the minimum item in s.
//
// If s is empty, Min returns the zero value.
//
//	Min([]int{1, 2, 3}) // 1
//	Min([]string{"a", "b", "c"}) // "a"
func Min[S ~[]E, E constraints.Ordered](s S) E {
	if len(s) == 0 {
		var zero E
		return zero
	}

	m := s[0]
	for _, item := range s {
		if item < m {
			m = item
		}
	}
	return m
}

// Max returns the maximum item in s.
//
// If s is empty, Max returns the zero value.
//
//	Max([]int{1, 2, 3}) // 3
//	Max([]string{"a", "b", "c"}) // "c"
func Max[S ~[]E, E constraints.Ordered](s S) E {
	if len(s) == 0 {
		var zero E
		return zero
	}

	m := s[0]
	for _, item := range s {
		if item > m {
			m = item
		}
	}
	return m
}

// Sum returns the sum of the items in s.
//
//	Sum([]int{1, 2, 3}) // 6
func Sum[S ~[]E, E constraints.Numeric](s S) E {
	var sum E
	for _, item := range s {
		sum += item
	}
	return sum
}

// Length returns the length of s.
//
//	Length([]int{1, 2, 3}) // 3
//	Length([]string{"a", "b", "c"}) // 3
func Length[S ~[]E, E any](s S) int {
	return len(s)
}
