// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: kratos/middleware/protovalidate/internal/proto/protovalidate/v1/person.proto

package protovalidatepb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Person struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Home          *Coordinates           `protobuf:"bytes,4,opt,name=home,proto3" json:"home,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_kratos_middleware_protovalidate_internal_proto_protovalidate_v1_person_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_middleware_protovalidate_internal_proto_protovalidate_v1_person_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_kratos_middleware_protovalidate_internal_proto_protovalidate_v1_person_proto_rawDescGZIP(), []int{0}
}

func (x *Person) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Person) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Person) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Person) GetHome() *Coordinates {
	if x != nil {
		return x.Home
	}
	return nil
}

type Coordinates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinates) Reset() {
	*x = Coordinates{}
	mi := &file_kratos_middleware_protovalidate_internal_proto_protovalidate_v1_person_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinates) ProtoMessage() {}

func (x *Coordinates) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_middleware_protovalidate_internal_proto_protovalidate_v1_person_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinates.ProtoReflect.Descriptor instead.
func (*Coordinates) Descriptor() ([]byte, []int) {
	return file_kratos_middleware_protovalidate_internal_proto_protovalidate_v1_person_proto_rawDescGZIP(), []int{1}
}

func (x *Coordinates) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Coordinates) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

var File_kratos_middleware_protovalidate_internal_proto_protovalidate_v1_person_proto protoreflect.FileDescriptor

const file_kratos_middleware_protovalidate_internal_proto_protovalidate_v1_person_proto_rawDesc = "" +
	"\n" +
	"Lkratos/middleware/protovalidate/internal/proto/protovalidate/v1/person.proto\x12\x10protovalidate.v1\x1a\x1bbuf/validate/validate.proto\"\xb2\x01\n" +
	"\x06Person\x12\x18\n" +
	"\x02id\x18\x01 \x01(\x04B\b\xbaH\x052\x03 \xe7\aR\x02id\x12\x1d\n" +
	"\x05email\x18\x02 \x01(\tB\a\xbaH\x04r\x02`\x01R\x05email\x12<\n" +
	"\x04name\x18\x03 \x01(\tB(\xbaH%r#(\x80\x022\x1e^[[:alpha:]]+( [[:alpha:]]+)*$R\x04name\x121\n" +
	"\x04home\x18\x04 \x01(\v2\x1d.protovalidate.v1.CoordinatesR\x04home\"c\n" +
	"\vCoordinates\x12)\n" +
	"\x03lat\x18\x01 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x80V@)\x00\x00\x00\x00\x00\x80V\xc0R\x03lat\x12)\n" +
	"\x03lng\x18\x02 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x80f@)\x00\x00\x00\x00\x00\x80f\xc0R\x03lngB\xa6\x01\n" +
	"\x14com.protovalidate.v1B\vPersonProtoP\x01Z protovalidate/v1;protovalidatepb\xa2\x02\x03PXX\xaa\x02\x10Protovalidate.V1\xca\x02\x10Protovalidate\\V1\xe2\x02\x1cProtovalidate\\V1\\GPBMetadata\xea\x02\x11Protovalidate::V1b\x06proto3"

var (
	file_kratos_middleware_protovalidate_internal_proto_protovalidate_v1_person_proto_rawDescOnce sync.Once
	file_kratos_middleware_protovalidate_internal_proto_protovalidate_v1_person_proto_rawDescData []byte
)

func file_kratos_middleware_protovalidate_internal_proto_protovalidate_v1_person_proto_rawDescGZIP() []byte {
	file_kratos_middleware_protovalidate_internal_proto_protovalidate_v1_person_proto_rawDescOnce.Do(func() {
		file_kratos_middleware_protovalidate_internal_proto_protovalidate_v1_person_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kratos_middleware_protovalidate_internal_proto_protovalidate_v1_person_proto_rawDesc), len(file_kratos_middleware_protovalidate_internal_proto_protovalidate_v1_person_proto_rawDesc)))
	})
	return file_kratos_middleware_protovalidate_internal_proto_protovalidate_v1_person_proto_rawDescData
}

var file_kratos_middleware_protovalidate_internal_proto_protovalidate_v1_person_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kratos_middleware_protovalidate_internal_proto_protovalidate_v1_person_proto_goTypes = []any{
	(*Person)(nil),      // 0: protovalidate.v1.Person
	(*Coordinates)(nil), // 1: protovalidate.v1.Coordinates
}
var file_kratos_middleware_protovalidate_internal_proto_protovalidate_v1_person_proto_depIdxs = []int32{
	1, // 0: protovalidate.v1.Person.home:type_name -> protovalidate.v1.Coordinates
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kratos_middleware_protovalidate_internal_proto_protovalidate_v1_person_proto_init() }
func file_kratos_middleware_protovalidate_internal_proto_protovalidate_v1_person_proto_init() {
	if File_kratos_middleware_protovalidate_internal_proto_protovalidate_v1_person_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kratos_middleware_protovalidate_internal_proto_protovalidate_v1_person_proto_rawDesc), len(file_kratos_middleware_protovalidate_internal_proto_protovalidate_v1_person_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kratos_middleware_protovalidate_internal_proto_protovalidate_v1_person_proto_goTypes,
		DependencyIndexes: file_kratos_middleware_protovalidate_internal_proto_protovalidate_v1_person_proto_depIdxs,
		MessageInfos:      file_kratos_middleware_protovalidate_internal_proto_protovalidate_v1_person_proto_msgTypes,
	}.Build()
	File_kratos_middleware_protovalidate_internal_proto_protovalidate_v1_person_proto = out.File
	file_kratos_middleware_protovalidate_internal_proto_protovalidate_v1_person_proto_goTypes = nil
	file_kratos_middleware_protovalidate_internal_proto_protovalidate_v1_person_proto_depIdxs = nil
}
