name: Go Lint

on:
  push:
    branches:
      - 3.x
  pull_request:
    branches:
      - 3.x

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Go mod cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-mod

      - name: Tools cache
        uses: actions/cache@v4
        env:
          cache-name: go-tools-cache
        with:
          path: .tools
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('./internal/tools/**') }}

      - name: GolangCI-Lint cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/golangci-lint
          key: ${{ runner.os }}-golangci-lint-${{ hashFiles('**/.golangci.yml') }}
          restore-keys: ${{ runner.os }}-golangci-lint-

      - uses: actions/setup-go@v6
        with:
          go-version: stable
          check-latest: true
          cache: false

      - name: Run lint
        run: make lint

      - name: Build
        run: make build

      - name: Check clean repository
        run: make check-clean-work-tree