name: Go Lint

on:
  push:
    branches:
      - 3.x
  pull_request:
    branches:
      - 3.x

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: stable
          check-latest: true
          cache-dependency-path: "**/go.sum"

      - name: Tools cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        env:
          cache-name: go-tools-cache
        with:
          path: .tools
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('./internal/tools/**') }}

      - name: Run lint
        run: make lint

      - name: Build
        run: make build

      - name: Check clean repository
        run: make check-clean-work-tree