name: Go Lint

on:
  push:
    branches:
      - 4.x
  pull_request:
    branches:
      - 4.x

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v6
        id: setup-go
        with:
          go-version-file: go.mod
          check-latest: false
          cache: false

      - name: Go cache
        uses: actions/cache@v6
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-${{ runner.arch }}-go-${{ steps.setup-go.outputs.go-version }}-${{ hashFiles('**/go.mod', '**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-go-${{ steps.setup-go.outputs.go-version }}-

      - name: GolangCI-Lint cache
        uses: actions/cache@v6
        with:
          path: ~/.cache/golangci-lint
          key: ${{ runner.os }}-golangci-lint-${{ hashFiles('**/.golangci.yml') }}
          restore-keys: ${{ runner.os }}-golangci-lint-

      - name: Run lint
        run: make lint

      - name: Build
        run: make build

      - name: Check clean repository
        run: make check-clean-work-tree
